import './style.css';
import './touch.css';

type DemoAction = { label: string; kind: string; destructive?: boolean; done?: boolean };
const sampleActions: DemoAction[] = [
  { label: 'Save address', kind: 'button' }, { label: 'Shipping method', kind: 'field' }, { label: 'Review order', kind: 'link' }, { label: 'Delete saved draft', kind: 'button', destructive: true }
];
const app = document.querySelector<HTMLDivElement>('#app')!;
const base = 'https://speak-page-actions.sociobot.in';
const route = () => location.pathname.replace(/\/$/, '') || '/';
const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]!));
function setMeta(title: string, description: string, canonical = route()) { document.title = title; document.querySelector('meta[name="description"]')?.setAttribute('content', description); document.querySelector('link[rel="canonical"]')?.setAttribute('href', `${base}${canonical}`); }
function shell(content: string, active = '') {
  return `<a class="skip" href="#main">Skip to main content</a><header class="site-header"><a class="wordmark" href="/" aria-label="Speak Page Actions home"><span aria-hidden="true">●</span> Speak Page Actions</a><nav aria-label="Main navigation"><a href="/demo" ${active === 'demo' ? 'aria-current="page"' : ''}>Demo</a><a href="/downloads/speak-page-actions.zip" download>Download</a><a href="/privacy" ${active === 'privacy' ? 'aria-current="page"' : ''}>Privacy</a></nav></header>${content}<footer><p>Speak visible page actions with review before sensitive clicks.</p><nav aria-label="Footer navigation"><a href="/privacy">Privacy</a><a href="/terms">Terms</a><span>Built by Param Factory</span></nav><small>v1.0.0 · Original generated illustration disclosed above.</small></footer><div id="route-note" class="sr-only" aria-live="polite"></div>`;
}
function home() {
  setMeta('Speak Page Actions — Speak visible page actions', 'Speak visible page actions with review before sensitive clicks.');
  app.innerHTML = shell(`<main id="main" tabindex="-1"><section class="hero"><div class="hero-copy"><p class="kicker">A small command layer for ordinary pages</p><h1>Speak the action you need</h1><p class="lede">For people with limited vision or hand mobility, it turns visible page labels into reviewable voice actions.</p><div class="hero-actions"><a class="button primary" href="/demo">Try it with sample data</a><span>Opens a safe sample page in one click.</span></div><ul class="facts" aria-label="Product facts"><li>Page labels stay in your browser</li><li>Works offline after the first visit</li><li>Core actions stay free; Pro aliases cost $12 once</li></ul></div><figure><img src="/art/hero.webp" width="1200" height="800" fetchpriority="high" decoding="async" alt="A printed browser page with a sound wave becoming a pointer." /><figcaption>Original generated artwork, made for Speak Page Actions.</figcaption></figure></section><section class="product-preview" aria-labelledby="preview-title"><div><p class="kicker">What the extension shows</p><h2 id="preview-title">A short list you can check</h2><p>It reads buttons, links, and labelled fields already visible on the current page.</p></div><ol class="action-sample"><li><span>button</span> Save address</li><li><span>link</span> Review order</li><li class="warning"><span>review</span> Delete saved draft</li></ol></section><section class="steps" aria-labelledby="steps-title"><h2 id="steps-title">How Speak Page Actions works</h2><ol><li><strong>Open the extension.</strong><span>It scans the active page only.</span></li><li><strong>Hold to speak.</strong><span>Use on-device speech, or type a label you can review.</span></li><li><strong>Review sensitive actions.</strong><span>It asks before labels such as delete or publish.</span></li></ol></section><section class="limits" aria-labelledby="limits-title"><h2 id="limits-title">What it does not do</h2><p>It does not listen in the background. It never lists password fields.</p></section><section class="price" aria-labelledby="price-title"><p class="kicker">One-time pro license</p><h2 id="price-title">Keep your own command aliases</h2><p>Pro costs $12 once. It lets you save local aliases in the extension. Core page actions and safety checks stay free.</p><a class="button primary" href="https://api.sociobot.in/api/v1/products/speak-page-actions/checkout">Buy a $12 pro license</a><button class="link-button" id="restore">Have a license? Paste it</button><form id="license-form" hidden><label for="license">License token</label><input id="license" required autocomplete="off" /><button class="button" type="submit">Restore license</button></form><p id="license-status" role="status" aria-live="polite"></p></section></main>`);
  setupLicense();
}
function demo() {
  setMeta('Demo — Speak Page Actions', 'Try Speak Page Actions on a safe sample page.');
  const state = JSON.parse(localStorage.getItem('demo:spa:sample') || '{"actions":[]}');
  const actions = state.actions.length ? state.actions : sampleActions;
  app.innerHTML = shell(`<div class="demo-bar" role="status">Demo — sample data, nothing is saved <button id="reset-demo">Reset demo</button><a href="/">Start for real</a></div><main id="main" tabindex="-1" class="demo-main"><p class="kicker">Sample checkout page</p><h1>Speak a visible page action</h1><p class="lede">Hold the mic in the extension, or test the same command below.</p><section class="demo-console" aria-labelledby="demo-title"><div><h2 id="demo-title">Visible actions on this page</h2><p>Try “click save address” or “click delete saved draft”.</p></div><label for="demo-command">Type a command for the sample</label><div class="command"><input id="demo-command" placeholder="click save address" /><button id="run-demo" class="button primary">Run command</button></div><p id="demo-status" role="status" aria-live="polite">Ready for a command.</p><ul id="demo-actions">${actions.map((action: DemoAction) => `<li><button data-action="${escapeHtml(action.label)}"><span>${action.kind}</span>${escapeHtml(action.label)}${action.destructive ? '<b> review</b>' : ''}</button></li>`).join('')}</ul><button id="demo-undo" class="button" hidden>Undo last page action</button></section><section class="demo-note"><h2>This is a safe sample</h2><p>Reset restores four sample actions. Demo state uses the separate <code>demo:spa:</code> browser storage namespace.</p></section></main>`, 'demo');
  setupDemo(actions);
}
function legal(kind: 'privacy' | 'terms') {
  const privacy = kind === 'privacy'; setMeta(`${privacy ? 'Privacy' : 'Terms'} — Speak Page Actions`, privacy ? 'How Speak Page Actions handles local browser data.' : 'Terms for Speak Page Actions.');
  app.innerHTML = shell(`<main id="main" tabindex="-1" class="legal"><p class="kicker">Speak Page Actions</p><h1>${privacy ? 'Privacy that stays close to your page' : 'Terms for Speak Page Actions'}</h1>${privacy ? '<h2>What the extension reads</h2><p>The extension reads visible labels, roles, and control types on the active page after you open it. It does not read password fields.</p><h2>What stays on your device</h2><p>Settings and license tokens are stored in your browser. The product sends no page labels, spoken words, or browsing history to our servers.</p><h2>When a network request happens</h2><p>Only a buyer’s license token may be checked with Sociobot. The demo makes no request beyond this site.</p><h2>Contact</h2><p>Questions about this policy can be sent through the factory product page.</p>' : '<h2>Using the extension</h2><p>Speak Page Actions helps operate ordinary pages. You remain responsible for reviewing and confirming any page action.</p><h2>License</h2><p>Pro is a one-time license. Sociobot and Dodo are the merchant of record. Refunds and revoked licenses are handled through the checkout provider.</p><h2>No warranty</h2><p>Browser pages change often. The extension may not identify every control or undo actions after a page navigates.</p>'}</main>`, kind);
}
function notFound() { setMeta('Page not found — Speak Page Actions', 'The page you requested could not be found.'); app.innerHTML = shell(`<main id="main" tabindex="-1" class="not-found"><p class="kicker">404</p><h1>This page could not be found</h1><p>The address may have changed. Return home to learn about visible page actions.</p><a class="button primary" href="/">Return home</a></main>`); }
function setupDemo(actions: DemoAction[]) {
  let last: DemoAction | undefined; const status = document.querySelector('#demo-status')! as HTMLElement;
  const run = (label: string) => { const target = label.toLowerCase().replace(/^(click|press)\s+/, ''); const action = actions.find((item) => item.label.toLowerCase() === target || item.label.toLowerCase().includes(target)); if (!action) { status.textContent = 'No visible action matched. Use a label from the list.'; return; } if (action.destructive && !confirm(`Review: “${action.label}” may change this sample page. Use it?`)) { status.textContent = 'The action was not used.'; return; } last = action; status.textContent = `Used ${action.label}.`; (document.querySelector('#demo-undo') as HTMLButtonElement).hidden = false; localStorage.setItem('demo:spa:sample', JSON.stringify({ actions })); };
  document.querySelector('#run-demo')?.addEventListener('click', () => run((document.querySelector('#demo-command') as HTMLInputElement).value)); document.querySelector<HTMLInputElement>('#demo-command')?.addEventListener('keydown', (event: KeyboardEvent) => { if (event.key === 'Enter') run((event.currentTarget as HTMLInputElement).value); }); document.querySelectorAll<HTMLButtonElement>('[data-action]').forEach((button) => button.addEventListener('click', () => run(button.dataset.action!))); document.querySelector('#demo-undo')?.addEventListener('click', () => { status.textContent = last ? `Undid ${last.label} in the sample.` : 'There is no sample action to undo.'; (document.querySelector('#demo-undo') as HTMLButtonElement).hidden = true; }); document.querySelector('#reset-demo')?.addEventListener('click', () => { localStorage.removeItem('demo:spa:sample'); location.reload(); });
}
function setupLicense() {
  const key = 'sb_license:speak-page-actions'; const saved = new URLSearchParams(location.search).get('license'); if (saved) { localStorage.setItem(key, saved); history.replaceState({}, '', location.pathname); }
  const form = document.querySelector<HTMLFormElement>('#license-form'), restore = document.querySelector<HTMLButtonElement>('#restore'), status = document.querySelector<HTMLElement>('#license-status');
  const verify = async (token: string) => { const cached = JSON.parse(localStorage.getItem('spa:license-verdict') || 'null'); if (cached?.valid && Date.now() - cached.checkedAt < 86_400_000) { status!.textContent = 'Your pro license is active.'; return; } status!.textContent = 'License saved on this device. Checking it now.'; try { const response = await fetch(`https://api.sociobot.in/api/v1/products/speak-page-actions/verify?license=${encodeURIComponent(token)}`); const result = await response.json(); localStorage.setItem('spa:license-verdict', JSON.stringify({ ...result, checkedAt: Date.now() })); status!.textContent = result.valid ? 'Your pro license is active.' : 'This license is not active. You can buy a new license.'; } catch { status!.textContent = cached?.valid ? 'Your cached pro license is active. It will be checked when you are online.' : 'License saved. It will be checked when you are online.'; } };
  const existing = localStorage.getItem(key); if (existing) verify(existing); restore?.addEventListener('click', () => form!.hidden = !form!.hidden); form?.addEventListener('submit', async (event) => { event.preventDefault(); const token = (document.querySelector('#license') as HTMLInputElement).value.trim(); if (!token) return; localStorage.setItem(key, token); await verify(token); });
}
const pages: Record<string, () => void> = { '/': home, '/demo': demo, '/privacy': () => legal('privacy'), '/terms': () => legal('terms'), '/404': notFound };
function render(moveFocus = false) { (pages[route()] || notFound)(); requestAnimationFrame(() => { const heading = document.querySelector('h1') as HTMLElement; heading?.setAttribute('tabindex', '-1'); if (moveFocus) heading?.focus({ preventScroll: true }); document.querySelector('#route-note')!.textContent = document.title; }); }
document.addEventListener('click', (event) => { const link = (event.target as HTMLElement).closest('a[href]') as HTMLAnchorElement | null; if (!link || link.origin !== location.origin || link.hasAttribute('download')) return; event.preventDefault(); history.pushState({}, '', link.pathname); render(true); window.scrollTo(0, 0); }); window.addEventListener('popstate', () => render(true)); if ('serviceWorker' in navigator) navigator.serviceWorker.register('/service-worker.js').catch(() => undefined); render();
